name: hacker-news-lark-push

on:
  schedule:
    - cron: "0 2 * * 1-5"
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16]
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 7.0.0-rc.3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
      
    - name: Send Push
      run: |
        LARK_HOOK_URL='${{ secrets.LARK_HOOK_URL }}' pnpm run start
  
