name: hacker-news-lark-push

on:
  schedule:
    - cron: "0 2 * * 1-5"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18]
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4.0.0
      with:
        version: 7.0.0-rc.3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install

    - name: Send Push
      run: |
        LARK_SCERCT='${{ secrets.LARK_SCERCT }}' npm run start

